# Generated by Django 3.2.8 on 2021-10-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhut', '0002_auto_20211030_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='when',
            field=models.DateTimeField(verbose_name='date created'),
        ),
    ]
